site_name: Ashe
site_url: http://noriah.github.io/ashe/
site_description: 'Ashe: A library for accessing the riot api based loosely around lol-js'
site_author: 'noriah <vix@noriah.dev>'
site_dir: out/docs

copyright: © 2016 noriah
include_next_prev: False

use_directory_urls: False
docs_dir: docs/src

repo_url: https://github.com/noriah/ashe/

google_analytics: ['UA-80482110-1', 'noriah.github.io']

theme: readthedocs

markdown_extensions:
  - sane_lists
  - smarty
  - toc:
      anchorlink: False
      permalink: True
      separator: "_"

pages:
  - Home: index.md
  - Usage: usage.md
  - Docs: docs.md
